os:
  - linux
language: csharp
mono: none
dotnet: 2.1
before_script:
- dotnet restore
- export PATH="$PATH:$HOME/.dotnet/tools"
- dotnet tool install --global dotnet-sonarscanner --version 4.6.0
script:
- bash ./build/ci.sh